neo4j-documentation/docs-ui

- .eslintrc
- gulpfile.js
- preview-src/training-enrollment.adoc
- preview-src/ui-model.yml
- src/css/training.css
- src/js/21-graphacademy-enrollment.js
- src/layouts/training-enrollment.hbs
- src/partials/footer-scripts.hbs
> Integrate Marketo form to enroll in course

- README.adoc
- src/css/landing.css
- src/css/training.css
|**Before**|**After**|
|--|--|
|![localhost_8000_graphacademy_university-program_(Laptop with MDPI screen) (1)](https://user-images.githubusercontent.com/333276/99988436-eb97fd80-2db1-11eb-873e-3ec2ebdd4bfa.png)|![localhost_8000_graphacademy_university-program_(Laptop with MDPI screen)](https://user-images.githubusercontent.com/333276/99988452-ee92ee00-2db1-11eb-9336-93857686d276.png)
> Style improvements related to the new GraphaAcademy documentation component

- src/css/training.css
> Style the list of featured courses on the /graphacademy page

- preview-src/applied-graph-algo-course-yelp.adoc
- preview-src/ui-model.yml
- src/css/training.css
- src/js/23-yelp-agreement.js
This code is highly specific to the "Applied Graph Algo" course where the student needs to agree to the Yelp license agreement before creating a sandbox instance on https://sandbox.neo4j.com
Here's the result:
//cc @ElaineRosenberg
> Add a Yelp Dataset Agreement component

- src/partials/header-content.hbs
This PR adds the arrows project into the Labs header
> Add arrows in Labs header

- src/partials/footer-content.hbs
> Fix static links

- preview-src/training-enrollment-disabled.adoc
- preview-src/ui-model.yml
- src/js/21-graphacademy-enrollment.js
- src/layouts/training-enrollment.hbs
resolves #29
//cc @ElaineRosenberg
> resolves #29 show a message if enrollment is disabled

- src/partials/head-prelude.hbs
> resolves #31 noindex on googlebot and bingbot when page-no-index is defined

- src/css/neo4j-docs.css
Allows use of labels such as Enterprise Edition in more places, eg list items.
> update labels in docs css

- package-lock.json
- src/css/doc.css
- src/js/21-graphacademy-enrollment.js
- src/js/24-graphacademy-certification.js
Register event listeners on `body.training-enrollment` or `body.training-certification` (otherwise enrollment event listeners are "overridden" by certification event listeners!)
> Fix event conflicts

- preview-src/first-steps-with-cypher.adoc
- preview-src/ui-model.yml
- src/css/code.css
- src/css/gram.css
- src/js/07-runnable-code.js
- src/js/modules/graph.js
- src/js/modules/runnable.js
- Add a new page with multiple setup queries (http://localhost:5252/first-steps-with-cypher.html)
- Run instant Cypher queries sequentially
- Hide the "Run Query" button on "single" runnable elements
- Show raw result when there's no data
- Remove links that have reference (target or end) on non-existing nodes
> Improve runnable code blocks for GraphGists

- preview-src/index.adoc
- src/css/labels.css
As I accidentally included changes to package-lock.json in my previous PR, this PR replaces #62.
> same as previous pr but minus the accidental changes to package-lock

- src/js/modules/runnable.js
> resolves #65 fix data format

- src/js/modules/runnable.js
> resolves #61 display query stats

- preview-src/docs-roles.adoc
- src/css/neo4j-docs.css
This class is intended for use by GDS to mark functions
> Add .feature-referene CSS class

- src/partials/kb-header.hbs
This PR fixes a small typo to the /kb search options. @adam-cowley
> fix kb search options

- preview-src/docs-roles.adoc
- src/css/neo4j-docs.css
Co-Authored-By: Mats Rydberg <mats@neotechnology.com>
> Add styles for GDS graph variants display

- src/css/header.css
- src/css/nav.css
- src/css/themes.css
- src/css/vars.css
- src/partials/header-content.hbs
This PR replaces the "Try Neo4j" with a "Get Started CTA" like on neo4j.com and styles as close as possible with as minimal additional CSS as possible
> redesign nav getting started CTA

- preview-src/docs-index.adoc
- src/css/nav.css
- src/css/vars.css
- src/partials/nav-menu.hbs
- Also add option to not display component title in nav (eg for docs-home layout pages)
> Reduce nav line height

- src/partials/header-content.hbs
Depends upon https://github.com/neo-technology/neo4j.com/pull/832
> Remove the Aura pages from developer guides

- src/css/docs-home.css
- src/css/nav.css
Creates a nav for pages with the docs-home page theme that allows us to list everything without the navigation growing too long.
> Docs home nav

- preview-src/docs-roles.adoc
- src/css/labels.css
Adds a label to be used in Neo4j procedures documentation, to mark procedures with `@Admin`
> Add role-admin as a label

- preview-src/index.adoc
- src/css/neo4j-docs.css
Use the same formatting as `statsonlyqueryresult`
> Format erroronlyqueryresult paragraphs

- src/css/nav.css
> Add padding to list items with data depth 5

- src/js/06-code.js
> Make code blocks expandable by clicking anywhere on them

- preview-src/index.adoc
- src/partials/article.hbs
```
:page-deprecated-title: the Getting Started Manual
:page-deprecated-redirect: https://neo4j.com/docs/getting-started/current/
```
> Deprecation Notices

- preview-src/index.adoc
- src/css/code.css
- src/css/doc.css
- src/css/glossary.css
- src/css/vars.css
- src/js/06-code.js
- Removes 'Run in Neo4j Browser'
- Moves the 'copy' button into the codeblock and out of the header
- Minor related margin, padding changes
> Update codeblock style

- preview-src/docs-roles.adoc
- src/css/neo4j-docs.css
- src/js/60-docs-roles.js
- src/partials/head-meta.hbs
- header padding
- inline element spacing in headers
- `og:description` meta tag
> Fix ui bugs

- src/css/code.css
- src/css/doc.css
- src/css/vars.css
- src/js/06-code.js
- src/js/50-cheat-sheet-toggle.js
Fixes issues introduced by cheat sheet selector and updates to codeblocks.
> Fix codeblock regression and bug

- src/partials/navbar-end.hbs
New pages added in PR neo4j-documentation/labs-pages/pull/38
> Add neomodel to labs menu

- preview-src/tables-no-captions.adoc
- preview-src/ui-model.yml
- src/css/doc.css
Hides table captions (but keeps them in the page for accessibility) when `:page-styles: hide-table-captions` is added to the document header.
> Hide table captions

- src/css/docs-home.css
- src/css/neo4j-docs.css
Sister PR https://github.com/neo-technology/docs-home/pull/74
> Rename `.drivers-apis` to `.create-applications` after renaming in docs-home

- src/css/doc.css
> Uniform inline code style for callouts

- src/css/doc.css
> Add style for `summary` tag

- src/css/neo4j-docs.css
> Add image class `rounded-corners`.

- src/css/doc.css
More specific rules will be used in the chatbot css
> revert the css revert for chatbot styles

- src/partials/navbar-end.hbs
I've marked this as draft so we don't merge it before the Neodash commercial docs are published to neo4j.com
> Add Neodash commercial

- src/css/themes.css
- src/js/70-docs-ndl.js
Add classes to links in cards and the banner on neo4j.com/docs so that we can track clicks on those links accurately as linkClicks in GTM.
- Adds `banner-link` class to `<a>` tags inside a div with class `banner`.
- Adds `card-link` class to `<a>` tags inside a `.link` div in a `.cards` div beneath the banner
> add card-link and banner-link class for tracking

- src/css/research.css
> Changing cursor when hovering link

- src/partials/navbar-end.hbs
https://trello.com/c/FP4SfXdS/151-add-a-customer-support-section-on-the-drop-down-for-getting-help + new link for new video page
> Get help header dropdown changes
