neo4j-documentation/docs-ui

- preview-src/kb-index.adoc
- preview-src/ui-model.yml
- src/css/header.css
- src/css/kb.css
- Preserve padding between Neo4j logo and "KB" title
- Add a small padding on the "Browser By Category" section
|**Current**|**New**|
|--|--|
|![neo4j com_developer_kb_(Moto G4) (1)](https://user-images.githubusercontent.com/333276/99646934-66c77f80-2a51-11eb-9a3b-0bc1feb7beec.png)|![localhost_5252_kb-index html(Moto G4)](https://user-images.githubusercontent.com/333276/99646635-03d5e880-2a51-11eb-8491-33d1424e03dc.png)
> Improve KB styling on mobile

- src/partials/edit-this-page-link.hbs
- src/partials/toolbar.hbs
In a playbook or asciidoc source file set the attribute `page-origin-private: true` to prevent the 'Edit this page' link from being included in the output.
> Toolbar add page origin private

- src/partials/page-versions.hbs
We publish a preview set of docs for the next version alongside the existing versions, at `/<version>-preview/` but we don't want that surfaced in the version picker, so we mark it as `prerelease:true` in antora.yml and exclude it from the list.
> add unless to page-versions

- preview-src/deprecated.adoc
- preview-src/docs-roles.adoc
- preview-src/ui-model.yml
- src/css/neo4j-docs.css
- src/css/site.css
- src/css/vars.css
- src/layouts/default.hbs
Adds css for Neo4j docs, adding a 'deprecated' admonition and allows attributes to be set at the page level to identify content as eg 'Enterprise Edition', 'Fabric', 'Deprecated', and also apply similar styling to h2, h3 etc (eg [here](https://neo4j.com/docs/operations-manual/current/performance/disks-ram-and-other-tips/)).
If you have recommendations for cleaning up the css I will welcome any suggestions!
> Neo4j docs css

- preview-src/private-page.adoc
- preview-src/ui-model.yml
- src/partials/head-gtm.hbs
- src/partials/head-info.hbs
- src/partials/head-meta.hbs
- src/partials/head-prelude.hbs
- src/partials/head-scripts.hbs
- src/partials/head-title.hbs
- src/partials/head.hbs
This PR includes updates that were requested by the web team.
- There are two possible inclusions of a canonical tag. I've commented one out and added an unless to exclude the other from docs
- Added swiftype tags for docs
- Modified og:title and `<title>...</title>` to match our old format for docs
- Moved head-scripts up
- Updated the toolbar to improve the Docs dropdown section and provide correct links to the Driver Manual or manuals for the current page
> Head fixes

- preview-src/drivers-tabs.adoc
- preview-src/ui-model.yml
- src/js/06-code.js
- src/js/06-tabs-block.js
This adds function for the tabbed sections that you see in the Drivers Manual up to Neo4j 4.1.
Although it's similar to (and based on) the function you've already added, because of the specific structure of the asciidoc blocks that form the tabbed content, and because that is no longer used in Neo4j 4.2, I felt it was better to keep it separate from the existing function.
> Add Drivers Manual code tabs

- src/partials/header-content.hbs
The official Go driver for 4.2 has just been released. This adds a link to the manual in the header.
> Add link to new Go manual

- src/js/07-feedback.js
The message after negative feedback to help us by editing the page is only applicable for content in a public repo. This adds a condition so the message is displayed only when applicable.
> Include additional feedback suggestion to user only for public and editable pages

- preview-src/drivers-tabs.adoc
- src/js/06-tabs-block.js
Adds the GDS modes to the list of 'langs' that can be tabbed.
Also, GDS prefer to display the tab even when there is only one tab, for example in [Collapse Path](https://neo4j.com/docs/graph-data-science/1.5-preview/alpha-algorithms/collapse-path/). This PR displays the single tab if the 'lang' is a GDS mode.
> Add tabbed sections in GDS documentation

- .gitignore
- src/css/vars.css
This PR updates the body and nav font weight to 400. The var.css file has been updated for this.
The current font weight for body is 200 which is too light and not easily readable. It is also not web accessible and elderly people and people with any eye problems would find it difficult to read. We recently updated the font-weight to 400 of the main neo4j.com website for the same reasons. And we would like to do it for the docs section as well.
> Update global font weight to 400

- preview-src/tables.adoc
- src/css/doc.css
The default Antora table word-break can cause parameter names to wrap, which does not look good.
```
.doc th.tableblock,
.doc td.tableblock {
word-break: break-word; /* overflow-wrap for table cells; gives space higher precedence than hyphen opportunity */
}
```
This can occur with reasonable column widths specified for a table.
I've spent some time trying to find an alternative, and this update changes the word-break from a condition applied to all table cells, and applies it to code and anchors in the cells instead. This prevents large codeblocks from exapnding the table, and covers the situation where we use a value or parameter of some kind as link text, but where it has not been formatted as code.
I don't know if this is _the_ solution, but I'm yet to find anything better. A spot …
> Alter conditions for word-break text in tables

- src/js/08-tabs-block.js
The GDS modes are ordered alphabetically when presented in tabs. GDS have requested this is changed to the order as shown in this PR.
> Reorder GDS modes in tabs

- preview-src/drivers-tabs.adoc
- src/js/08-tabs-block.js
Modifies tabs block so that once you've defined a `[.tabbed-example]` section you can append any text to `include-with-` to define a new tab. Unless stated in the js the tab title is initial-capitalized.
Although I think this can be merged as-is, there are two areas we could improve now/in future
1. For anything other than capitalization of the term, we need to update the switch statement. Is there a better way to handle that?
2. GDS displays a tab when there is only one tab, other projects currently don't. Could we define this with something like a page attribute in the playbook?
> Extend tabs

- src/partials/header-content.hbs
Adds links to the new Browser Manual and Desktop Manual, and puts them into a section called 'User Interface Tools' with Bloom.
> Add links to new Desktop and Browser manuals

- preview-src/index.adoc
- src/css/doc.css
The code a and a code will render the same.
Removed the visited styling.
> fixed link styling for code blocks

- preview-src/drivers-tabs.adoc
- src/js/08-tabs-block.js
Before this change `.include-with-stream-single-property` results in tab title `Stream-single-property` which is not very user-friendly.
> Replace hyphens with empty spaces for tabbed examples

- src/css/doc.css
The margin is already defined and the override makes the text under the block to get too close to the last element.
> Remove overriding margin style for .doc .colist

- preview-src/example.adoc
- preview-src/ui-model.yml
- src/css/doc.css
Adds a border to example blocks to allow them to be distinguished from surrounding content, which becomes useful when example blocks are long and contain other asciidoc blocks.
> Example border

- src/css/labels.css
Updates labels.css for the new classes added in #85 
Also adds vertical spacing to labels in .`tableblock` for when labels don't fit in the horizontal space.
> Fix removed css vars

- preview-src/ui-model.yml
- src/css/nav.css
Also reduces the left padding a bit on subsections and ensures right-padding is enough to stop text overlaying background
> maintain vertical align of arrow when title overflows

- src/css/graphgists.css
Otherwise, the input is misaligned with the button in Safari:
> Set fixed height for Safari

- src/js/13-search.js
Otherwise, we cannot type the character `/` is the "Connection URL" input field on a GraphGist page: https://neo4j.com/graphgists/first-steps-with-cypher/
//cc @jexp
> Disable search shortcut when editing input

- preview-src/tables.adoc
- src/css/doc.css
Adds a `no-break` style for tables.
Prevents text from wrapping, which can be useful if you have parameter names in a column and don't want the text to wrap.
The style applies to all columns in the table, so it will often be worth trying to adjust column widths first, before using this style.
Use `role="no-break"` in the table setup, eg
```
.Table
[role="no-break",opts="header",cols="1,1,4"]
|===
...
|===
```
> add no-break class for tables

- src/partials/nav-tree.hbs
hasString didn't match the helper, resulting in a fatal error.
> rename hasString to has-string to fix fatal error

- preview-src/index.adoc
- src/js/06-code.js
On pages like [Operations manual -> Clustering](https://neo4j.com/docs/operations-manual/4.3/docker/clustering/), Copy to clipboard resulted in broken code because of character escaping (eg `<` to `&lt;`) and the callouts were included.
Using `element.innerText` looks safe and reliable, keeps characters unescaped, and excludes callouts from the copied content.
> use innerText of code block for copy

- src/partials/header-content.hbs
Adds a link to AuraDS in the Docs > Aura menu.
> Add AuraDS to docs drop-down

- src/partials/head-meta.hbs
Allows page attributes specified in the header to be used in meta tags:
```
:page-ogdescription: This description is used in the og:descrption meta tag
:page-ogtitle: This title is used in the og:title meta tag
```
(ogtitle is already available in the ui - this adds ogdescription)
> add ogdescription as detectable page attribute

- preview-src/tables.adoc
- src/partials/head-meta.hbs
When `:page-ogtitle:` is specified in the document header, we want to use that value as-is for the meta tag.
This update prevents ` - <COMPONENT_TITLE>` from being appended to the meta tag when `:page-ogtitle:` is specified.
To verify, check that the meta tag for `/tables` does not have ` - Project XYZ` added:
`<meta property="og:title" content="This page uses the page-ogtitle attribute to generate a custom title for SEO meta">`
> Remove component title from meta title if page-ogtitle is specified

- src/partials/page-versions.hbs
Adds event tracking for when a user switches from one version of a page to a different version of the page.
> track version switching

- preview-src/docs-roles.adoc
- src/css/doc.css
- src/css/neo4j-docs.css
- src/helpers/split-string.js
- src/partials/article.hbs
Requested by GDS
To verify, check that the [Docs roles page](https://deploy-preview-113--neo4j-docs-ui.netlify.app/docs-roles.html) lists multiple roles by the page title.
For smaller page widths, the roles are displayed below the title, above the in-page toc.
> Display multiple page role values with page title

- src/partials/header-content.hbs
The PR will remove the *Developer Guides* drop down menu, which appears at the top of each page within docs.
The pages themselves will still be available, but we'll be adding an admonition to the top of each page which says that this page is no longer being maintained, with signposting to the new location within the docs.
> Comment out the Developer Guides to remove them from the UI drop downs

- src/css/landing.css
Since we are already using a hero title
**Before**
**After**
> Hide page title on labs landing page

- src/css/code.css
- src/js/06-code.js
This is the current situation:
And this is the effect of this PR:
----
I have altered the way in which the divs in the code block are created, so that `languageDiv` comes now after `titleDiv`. 
A naive solution where `flex-grow: 1` is only given to `.code-title` is not enough as it breaks when there the example block has no title (the second one here)
that's why I have `flex-grow` on both elements, one at 1 and one at 1000.
> Swap order of language name and block title in code examples (language first)

- src/css/toc.css
Currently, on narrow screens the table of contents gets rendered at the top and without any visible separation from the page content:
With this PR, the design looks like this
> Add distance between embedded (mobile) toc and content

- src/js/06-code.js
Fix #132, result:
(it makes sense to set the width a few lines earlier, or the `Success` button gets shrunk).
> Restore original height after copy to clipboard button is clicked

- src/partials/header-content.hbs
I believe `Drivers and APIs` is meaningful internally, but doesn't give away too much information to newcomers. Eventually, I guess everybody realizes that if you are looking for info on how to use Neo4j with Python, you should click on `Python` in that list, but this just creates an extra second of confusion. The word `Driver` is not commonly used in software to refer to these sort of libraries, so I would take it away at least from the navigation menu.
I suggest renaming it to `Create applications`. We could also go for `Create applications with`, implying that each element of the list completes the title, but I don't quite like it. Another, **possibly my favorite**, that comes to mind is `Libraries and APIs` (though I imagine the drivers team might not be happy with this). I am not a …
> Rename drivers/apis section to "Create applications" in navigation

- package-lock.json
- package.json
- src/js/vendor/highlight.js
Fixes #127. Node dependency updated as well, to match minimum requirement from highlight.js. I've taken the chance to update our language includes and use `cypher` and `graphql` as provided by highlight packages. 
Rebuilt environment and nothing was broken, as far as I could tell.
@adam-cowley tag you mostly for you to be aware, as this has the impact of affecting many pages.
> Update highlight.js to v11

- src/partials/head-meta.hbs
Falls back to the same content that is used for the `og:title` meta tag if no `description` or `og:description` attribute is found.
> Uses titles if no description

- preview-src/docs-roles.adoc
- src/css/doc.css
- src/css/neo4j-docs.css
- src/js/60-docs-roles.js
- src/partials/article.hbs
Improves the appearance of roles when displayed against headers, by right-aligning them, as we do for the cheat sheet.
I'd like in future for us to remove the distinction, at least in appearance, between roles and labels, which are performing largely the same function.
> Section roles fix

- src/css/code.css
- src/css/doc.css
Fixes an issue where a long first line of content in a source block would clash with the language and copy button on hover.
> Prevent content overlap in source block

- preview-src/cheat-sheet.adoc
- preview-src/ui-model.yml
- src/css/cheat-sheet.css
- src/css/nav.css
- src/css/vars.css
- src/js/01-nav.js
- src/js/02-on-this-page.js
- src/js/06-code.js
- src/js/12-fragment-jumper.js
- src/js/50-cheat-sheet-toggle.js
- src/partials/footer-scripts.hbs
- src/partials/head-styles.hbs
- src/partials/header-content.hbs
- src/partials/nav-explore.hbs
- src/partials/nav-menu.hbs
- src/partials/nav-selectors.hbs
- src/partials/nav.hbs
Improves the cheat sheet experience when we have Aura and Neo4j cheat sheets published together. Will require a slight modification to playbooks:
asciidoc attributes are now:
```
page-cheatsheet-product: Neo4j
page-cheatsheet-products:
- name: 'Neo4j Community Edition'
class: 'neo4j-ce'
...
```
Will allow us to serve up the same cheat sheet html page at multiple locations, so it will be accessible at `neo4j.com/docs/cypher-cheat-sheet/<version>/<product>/` where `<version>` is 4 or 5, and `<product>` is eg `neo4j-ee`, `aura-dbe` etc
> Cheat sheet updates for Aura and Neo4j

- src/js/60-docs-roles.js
Updates to how roles are displayed next to headers caused a problem with the docs-home theme. 
This PR restores missing headers in docs home pages.
> fix missing headers in docs home theme

- src/partials/navbar-end.hbs
This PR updates the header CTA to match the rest of neo4j.com, by updating the text and link target, and removing the drop-down.
> Update header CTA

- src/css/docs-home.css
- src/css/neo4j-docs.css
Before
After
Reason is the effect of `[.display]` in the asciidoc, which doesn't get appended to the div closest to the h2.
This also has the effect of fixing the style of docs-archive as I suppose it was intention to have it from the start:
Sister PR
https://github.com/neo-technology/docs-home/pull/74
> Fix css selector nesting in drivers landing page

- src/css/doc.css
> Remove excessive padding-bottom in blockquotes.

- src/css/doc.css
The background reason lies in fixing the scrollbar when code blocks are embedded in summary tags, as in #180. The issue stems from `width: 100%`, and shifting all the surrounding style to the `pre` container fixes that and also removes an extra set of rules, by merging it with an already existent set. No conflicts or regressions noticed on a bunch of docsets I tested it against.
Before
After
> Fix code blocks style

- src/css/doc.css
This reverts https://github.com/neo4j-documentation/docs-ui/pull/181/files + removes the `width` property on code, which also fixes the issue raised in #181 and doesn't seem to cause any more. The issue with #181 is the broken fading for collapsed blocks:
> Fix regression in code blocks style

- preview-src/feedback-disabled.adoc
- preview-src/ui-model.yml
- src/partials/article.hbs
To disable feedback for a component or module, add an asciidoc attribute to the playbook or antora.yml: `page-disablefeedback: true`
To disable feedback on a specific page, add a header attribute to the page: `:page-disablefeedback: true`
> Add option to disable feedback

- src/css/doc.css
(The background is anyway overwritten by the background of the child elements.)
After
Before
> Leave alone color of code blocks within admonitions

- src/css/doc.css
Adds a border to the left of a collapsed-expanded section to delimit its content.
Before
After
> Improve `details` style.

- src/js/50-cheat-sheet-toggle.js
This PR works in conjunction with updates to redirects for the Cypher cheat sheet so that a URL in the form `/docs/cypher-cheat-sheet/current/match/` can be redirected to `/docs/cypher-cheat-sheet/current/auradb-enterprise#match`
> Rewrite cheat-sheet URLs to access page sections

- .eslintrc
- src/css/feedback.css
- src/css/vars.css
- src/js/11-feedback.js
- src/partials/article.hbs
- src/partials/feedback.hbs
- src/partials/nav.hbs
- widget moved to the left, and is part of the html output rather than being a floating js object. Because the right ToC has `position: sticky` and scrolls itself as you progress through a page, I was unable to leave the feedback on the right _and_ avoid it shadowing some content. I've made the nav on the left slightly smaller so people can't think there's anything underneath the feedback. It gets expanded to full height when the feedback vanishes.
- after leaving feedback, politely thanks you and vanishes within a couple seconds
- you _can't_ leave negative feedback without adding a message
- you _can_ leave a message to a positive feedback (but may also leave it empty)
- the user journey through docs pages is registered and submitted as part of their feedback
- taken away the `Edit this …
> Improve feedback widget

- package.json
Contains updates for cypher syntax highlighting for v5 https://github.com/highlightjs/highlightjs-cypher/pull/18
> Update highlightjs-cypher to 1.2.

- preview-src/code.adoc
- src/css/code.css
- src/css/vars.css
- src/js/vendor/highlight.js
(Color comes from Needle, but cannot use the css color vars directly because they embed an opacity of 1, which we want to be 0.5)
> Support for line highlighting in code blocks

- src/js/06-code.js
The pipe is excluded from content when copied through the Copy icon, causing it to be skipped when a code block like in the [Kafka docs](https://neo4j.com/docs/kafka/quickstart-connect/#_run_with_docker) is copied.
This PR seems to fix this behaviour, but I would like to understand what was the rationale for exclusion before applying it.
This change was introduced in https://github.com/neo4j-documentation/docs-ui/pull/204, but from the discussion I can't understand why the pipe was excluded as well.
> Remove pipe from replaced characters in callouts

- preview-src/drivers-tabs.adoc
- src/js/08-tabs-block.js
- src/js/12-fragment-jumper.js
When an ID is set on a block that is part of a tabbed group the tab switching and scroll happens as it does when a user clicks on a tab.
> switch tabs when id and hash is used

- preview-src/banner-note.adoc
- preview-src/banner-warning.adoc
- preview-src/docs-roles.adoc
- preview-src/ui-model.yml
- src/css/header.css
- src/css/nav.css
- src/css/toolbar.css
- src/css/vars.css
- src/layouts/default.hbs
- src/partials/header-content.hbs
```
:page-banner: note
:page-banner-text: Lorem ipsum dolor sit est.
:page-banner-link: https://neo4j.com/docs
:page-banner-link-text: Link text
```
`note` is the default, `warning` can also be used.
> Add a banner to a page

- src/js/06-code.js
- src/js/08-tabs-block.js
I think it's a bad UX if the page moves unexpectedly. When looking at examples, people may want to look at them together with the text leading to it, and they have to manually scroll back up to.
Before
After
Question for @adam-cowley and @recrwplay , if you remember from 4 years ago: why do we have both `[.tabs]` and `[.tabbed-example]`? 
I believe we are actively only using `[.tabbed-example]`. If that's the case, can I declutter and entirely remove the `[.tabs]` bit?
> Avoid autoscroll when changing tab in tabbed example.

- src/css/code.css
Reduces the size of tabs in code blocks, currently looks like 8 spaces ([example](https://neo4j.com/labs/genai-ecosystem/spring-ai/))
> Reduce tab-size

- preview-src/docs-roles.adoc
- src/js/60-docs-roles.js
Fixes an issue with some labels being wrongly parsed where the text before the first hyphen was used instead of the full label.
For example, `aura-db-enterprise` was being treated as `aura` because that is a valid label in rolesData.json.
There are essentially two types of labels:
- 'version' labels, where we want to use only the text before the hyphen, eg `new-5.20` for the label class and add the text after the hyphen as label text.
- all other labels, where we take the whole label text and use that for the label class, and take the label text from rolesData.json
This PR also fixes an issue with discrete headings.
Labels are no longer displayed on discrete headings.
> Fix bug in label parsing

- src/js/vendor/highlight.js
There's been an intermittent problem where `after:highlightElement` would not always fire and thus leave the `mark-line` comments untouched. This change hopefully fixes that.
> Fix code highlighting

- src/css/labels.css
- src/css/vars.css
To create visual difference between removals and deprecations. 
Result:
Spawned #241.
> Labels: make deprecated labels yellow, discontinued red.

- src/css/header.css
Before, all items are not visible in docs menu item  
After
> Enlarge docs header dropdown

- src/js/06-code.js
- src/js/08-tabs-block.js
Clicked tab gets centered to a third of viewport height.
> Fix tabbed examples scrolling behavior

- src/css/header.css
From viewport widths less than ~1300px down to the breakpoint at 1024px when the TOC is removed and accessed via the burger icon the Docs drop-down menu is partly off-screen because of the increased width.
Aligning dropdowns to the left prevents part of the docs dropdown from disappearing off the left of the viewport.
> Make  header docs dropdown fully visible at all widths

- preview-src/tables-no-toc.adoc
- preview-src/ui-model.yml
- src/js/02-on-this-page.js
At narrow page widths, when the main TOC is still visible, setting `:page-toclevel: -1` results in no in-page 'Contents' being displayed, but the HTML elements are still present, taking up width.
This can produce inconsistent page appearance:
- pages with no headings use the available width
- pages with headings, but the 'Contents' section removed use the width minus the width of the `<aside>`.
Note that this change has no effect on the page layout once the `<article>` (the main page content) reaches its maximum width.
> Remove toc sidebar when page-toclevels is -1

- preview-src/index.adoc
- src/js/06-code.js
Fixes an issue where adding `role=nocopy` to a code block was also removing the header.
It is now possible to use:
- `role=nocopy` to not display the copy icon
- `role=noheader` to not display the header
- `role=nocopy noheader` to not display both
> Fix nocopy and noheader behavior

- src/js/50-cheat-sheet-toggle.js
- src/partials/nav-selectors.hbs
Recent updates in the version selector, and previous changes that were specific to the cheat sheet, meant the version of the cheat that is being displayed was excluded from the version selector.
This PR fixes that and a bug in the code for defining the default product to display.
> Fix version selector bugs

- preview-src/docs-roles.adoc
- src/css/labels.css
- src/js/50-cheat-sheet-toggle.js
- src/js/60-docs-roles.js
- src/js/data/rolesData.json
- src/partials/nav-selectors.hbs
For new and deprectaed labels it is already possible to include a version number. Although we have a generic `beta` label that can be used to display just the text `Beta`, there is no way to display a version with the text, for example `Beta until 5.12`. 
This PR adds a new `label--beta-until-<version>` role to be used for beta labels where a version number is also required.
> Add beta-until label

- preview-src/labels.adoc
- src/partials/nav-selectors.hbs
In the version selector we currently prepend the version name (usually a number) with the word 'Version'.
This PR extends the version selector to allow a choice of:
- custom text
- no text
Two attributes are available to control the text that is displayed:
- `page-selector-label`
- `page-selector-hide-label`
These attributes should be set in the usual way by defining in a playbook, antora.yml, or in a page header.
To set custom text:
```
:page-selector-label: Custom version label
```
To have no text, ie just the version name:
```
:page-selector-hide-label: true
```
> Select custom label or hide label in selectors

- src/js/60-docs-roles.js
Fixes a bug where `role=label--deprecated` was not being displayed
eg https://neo4j.com/docs/cypher-manual/current/subqueries/call-subquery/#importing-with
Found a bug introduced in #254 that was treating deprecated as a role that required a version to be specified. Deprecated can be used with or without a version number.
> Deprecated fix

- src/css/doc.css
Remove double underline under glossary terms and uniform link style for links within glossary terms.
> Remove double underline under glossary terms.

- preview-src/docs-roles.adoc
- src/js/60-docs-roles.js
- src/js/data/rolesData.json
- src/partials/article.hbs
Properly handles roles with product names and versions
- `label--beta-until-bolt-1.0`
- `label--beta-until-1.0`
Also allows for `page-product` attribute to be used in labels.
If `:page-product: Neo4j`, for example, `label--new-5.22` is displayed as 'New in Neo4j 5.22'
> Full role handling

- src/js/50-cheat-sheet-toggle.js
- src/partials/nav-selectors.hbs
Fixes issues where the href and the product selector weren't correctly updated on staging or prod when a new value was selected.
> Fix url replacement in cheat-sheet

- preview-src/docs-ndl.adoc
- src/css/docs-ndl.css
Adjusts padding and alignment for the highlights widget, bringing better symmetry between the two layouts. (Also flips the order so that the first instance is `image <> list` and the second is `list <> image` to breakup the amount of left-aligned text earlier).
> Tweak icon and list spacing

- src/css/doc.css
Chatbot uses Needle styles.
Needle styles set `list-type: none` on `ol` and `ul`
We need to set styles for lists in `.doc` content.
> Restore list markers

- preview-src/labels.adoc
- src/css/labels.css
- src/js/data/rolesData.json
The page-role "Labs" is already used for the Labs template, so in order to use a Labs label in H2 in an upcoming page in docs, I thought this could be the way to fix it.
> Creation of a Labs label for a different page-role

- src/js/06-code.js
- src/js/08-tabs-block.js
Updates the tab scroll to take the elements position before and after all the tabs have been switched so that the difference can be used for the `scrollTo`. The `scrollTo` behavior changes to instant, because we are effectively masking the fact that the tab position would move without a scrollTo, and we are moving it back to where it was before the tab was clicked.
> fix tab position in viewport

- src/css/doc.css
- src/css/docs-ndl.css
- src/css/labels.css
- src/css/neo4j-docs.css
This PR fixes a few issues across docs from recent home page updates:
- restores margin above the `.content` element and `h1` to preserve whitespace between breadcrumbs and page content
- restores margins for all headers
- removes `height` property from labels to center-align text vertically
- comments out properties in labels that have no effect
- updates border-radius for pseudo-class labels to match other labels
> UI fixes afer homepage updates

- src/css/docs-ndl.css
Tiles in docs landing pages currently have a normal cursor, even when they are clickable. 
With this change, the cursor will be a hand (like on links) when the tile is clickable.
> Graphically clarify home tiles are clickable.

- src/partials/head-info.hbs
WIth this change, a canonical link will be added to the head of every page, for example `<link rel="canonical" href="https://neo4j.com/docs/status-codes/2025.01/">`.
> Restore canonical link

- preview-src/tables.adoc
- src/helpers/edit-url-text.js
- src/partials/edit-this-page-link.hbs
Allow different text for the 'edit this page' link.
- If the page attribute `page-edit-url-text` is set that value is used.
- If no attribute is set, the text is determined by the `page-theme`.
- For `docs` pages, the text will be "Raise an issue".
- For all other pages the text is "Edit this page".
- The default title is 'Docs Feedback' followed by the file path and branch or tag name that the feedback relates to. To replace the 'Docs Feedback' text, use the page attribute `page-edit-url-title`
- Use the page attribute `page-edit-url-body` to provide placeholder text in the body of the issue. The default text is`> Do not include confidential information, personal data, sensitive data, or other regulated data.`
- To add labels to the issue, use the page attribute `page-edit-url-labels` …
> helper to choose edit this page link text

- preview-src/sidebar-headings-ad.adoc
- preview-src/sidebar-headings-no-ad.adoc
- preview-src/sidebar-no-headings-ad.adoc
- preview-src/sidebar-no-headings-no-ad.adoc
- preview-src/ui-model.yml
- src/js/02-on-this-page.js
See the 'sidebar' section for pages that show the following examples:
- A page with no headings, and no ad
- A page with no headings, but there is an ad
- A page with headings, but there's no ad
- A page with both headings and an ad
> Always show an ad even if there are no page subheadings

- src/helpers/neo-canonical-current.js
Use `page.latest` or `page.version` to get a version to replace with `current`.
If the component has a single version there is no `page.latest`. If `version: ~` in antora.yml there is no page.version.
If there's no version to replace, return the canonicalUrl as is.
> Replace version with current if single version and version is defined

- README.adoc
Fix instructions for updating bundle version and creating the tag.
> Update bundle publish steps

- src/css/docs-ndl.css
- src/css/themes.css
> Visually clarify that links are clickable 

- preview-src/admonitions.adoc
- src/css/doc.css
- src/css/vars.css
I don't know if we have any admonitions that contain tables, and maybe we shouldn't. But just in case we do now or at any point...
> Style tables in admonitions

- src/partials/header-content.hbs
Pages currently have two stray tags - major browsers seem to render them well anyway, but there's no good reason to rely on that.
To fix the missing closing `</a>` in the logo link, I also incorporated the fact that we've retired developer guides, so that an extra logo (white logo on black background) is not needed anymore. If this assumption is not valid, I'll revise.
> Fix stray HTML tags.

- src/js/02-on-this-page.js
This PR is required by a future change to how roles on headings are handled.
Currently labels are processed by javascript when a page is loaded in a browser. We are adding an extension to convert roles into labels during the asciidoc to html conversion so that their metadata (dataset attributes) are part of the raw HTML and can be used by tools that parse the HTML.
This PR ensures that only the text content of the heading element is used for the entries in the 'Contents' nav section of a page.
> Ensure only heading element text is used

- preview-src/ui-model.yml
- src/js/02-on-this-page.js
A recent change to how the titles for Page Contents are generated created a bug in the Cheat Sheet where the titles were not displayed in the TOC, because the code was not correctly handling headings that contain links. We don't typically use links in headings in the docs (in fact it should possibly be a style guide recommendation to NOT use links in headings in other docs) but the cheat sheet makes extensive use of this to provide links to the relevant sections of the Cypher Manual.
This PR fixes the issue.
> fix cheat sheet toc
